Point discharge with diffusion example
thetisproject/thetis pull request #230
Opened 2021-01-25 12:04 UTC by jwallwork23

Following the closing of issue #188, this PR acts to check that the 2D steady state tracer solver works.

Convergence of the error due to evaluating two linear functionals is assessed under uniform mesh refinement. Convergence rates for the case `hydrodynamics=False` below.

![convergence_aligned](https://user-images.githubusercontent.com/22053413/105703479-3692d600-5f05-11eb-91a9-5509ae094264.png)
(Aligned source and receiver)

![convergence_offset](https://user-images.githubusercontent.com/22053413/105703516-427e9800-5f05-11eb-900c-41e1fca5d945.png)
(Offset source and receiver)

This could be a test, if that would be useful / there aren't too many similar tests.

2021-02-09 15:38 UTC, tkarna requested changes
Thanks for this! Looks good. As the script runs a convergence test this is more a test rather than an example? So would better fit under `test/tracerEq/`(?) rather than `examples/`. Otherwise only minor comments.

2021-02-09 15:38 UTC, tkarna commented on examples/point_discharge/point_discharge.py
> +                4: {'diff_flux': Constant(0.0)},  # Neumann
I think this is equivalent to omitting the boundary condition declaration (which implies that the boundary flux term is omitted).

2021-02-09 15:38 UTC, tkarna commented on examples/point_discharge/point_discharge.py
> +        be computed using quadrature.
a quadrature

2021-02-09 15:38 UTC, tkarna commented on examples/point_discharge/point_discharge.py
> +    Delta functions are not in H1 and hence do not live in the FunctionSpaces we
Could mention that the analytical solution involves a point source (dirac delta). And the analytical solution gives the tracer value at an arbitrary "receiver" location (if I got that right). Also the offset parameter is not explained, it moves the receiver y location to be on off-axis?

2021-02-09 15:38 UTC, tkarna commented on examples/point_discharge/point_discharge.py
> +        triple = (20.0, 7.5 if self.offset else 5.0, 0.5)
minor detail: took me a while to figure out what triple is, you could define a x,y,radius dict and pass **dict to ball.

2021-02-09 15:38 UTC, tkarna commented on examples/point_discharge/point_discharge.py
> +left-hand boundary, and the right-hand boundary remains open.
maybe mention here that this is a steady-state problem for which an analytical solution exists

2021-02-09 17:23 UTC, jwallwork23 commented
Thanks for the review, @tkarna. I think I addressed all your comments.

2021-02-10 07:31 UTC, tkarna approved these changes
Thanks, looks good!

2021-02-19 12:32 UTC, tkarna approved these changes

2021-02-19 12:34 UTC, merged