Use Pyadjoint tagging for solves
thetisproject/thetis pull request #261
Opened 2021-08-25 08:06 UTC by jwallwork23

In [Pyadjoint PR66](https://github.com/dolfin-adjoint/pyadjoint/pull/66) and [Firedrake PR2174](https://github.com/firedrakeproject/firedrake/pull/2174) I introduced optional tags for the Pyadjoint tape blocks associated with various high-level operations. Here I am applying them to the prognostic equation solves in Thetis, so that the blocks corresponding to these solves can be easily identified and extracted.

For example, this makes the extraction and plotting of adjoint solution fields associated with different equations straightforward.

2021-09-03 11:54 UTC, tkarna reviewed
Thanks, this looks all right to me.

2021-09-03 11:54 UTC, tkarna commented on thetis/rungekutta.py
> +            fname = f'{self.name}_k{i}'
Thanks we should use f strings where possible, most of these are from ages before such python features.

2021-09-03 15:13 UTC, stephankramer requested changes
Otherwise looks good, yeah

2021-09-03 15:40 UTC, jwallwork23 commented on thetis/options.py
> +    ad_block_tag = None
Good point, thanks Stephan.

2021-09-07 10:00 UTC, tkarna approved these changes
Thanks, all good now!

2021-09-07 11:35 UTC, merged