Fix Thetis checkpoint loading
thetisproject/thetis pull request #345
Opened 2023-08-02 15:41 UTC by stephankramer

Previously we loaded the mesh from checkpoint, then loaded the field into a temporary function based on that mesh, and then assigned it to the field on the solver object, which is based on whatever mesh the user provided us. This is no longer allowed (and is also unsafe).

Now we would ask the user to provide us with a mesh read from a checkpoint, and directly read in the field into a function based on that same mesh. To help the user achieve that, added a read_mesh_from_checkpoint() utility function. To discuss: one of the downsides of this approach is that it requires the user to point to a specific .h5 file, whereas load_state only requires the output directory (and adds `'hdf5/Velocity2d_000...'` etc.)

See also discussion https://github.com/firedrakeproject/firedrake/discussions/3053

Should also fix #336. Note that both the case where the user had already loaded the mesh from a checkpoint - because they needed to load some other preprocessed data like in #336 - but also the case where the user re-creates the mesh by reading from a .msh file and then calling load_state() are currently broken. This should fix both cases - but requires changing the setup to read the mesh from checkpoint for the latter case.

2023-08-03 05:03 UTC, jhill1 commented
Sounds good to me. Also need to edit the docs page to match this: https://github.com/thetisproject/thetis/blob/master/docs/source/outputs_and_visu.rst
Something like:
```
diff --git a/docs/source/outputs_and_visu.rst b/docs/source/outputs_and_visu.rst
index 45aea1c1..3bd6023d 100644
--- a/docs/source/outputs_and_visu.rst
+++ b/docs/source/outputs_and_visu.rst
@@ -98,15 +98,17 @@ Restarting a simulation
 ~~~~~~~~~~~~~~~~~~~~~~~
 
 If you have stored the required HDF5 files, you can continue a simulation
-using :py:meth:`~.FlowSolver.load_state` method, provided that you use the same
-mesh and the same number of MPI processes. This call replaces the
+using :py:meth:`~.FlowSolver.load_state` method, provided that you use the
+mesh from that checkpoint file. This call replaces the
 :py:meth:`~.FlowSolver.assign_initial_conditions` call.
 If initial conditions are not set, add ``load_state`` call above
 the :py:meth:`~.FlowSolver.iterate` call.
 
-In the simplest form, one only defines the export index that is used as initial
-condition::
+In the simplest form, the mesh needs to be loaded from a HDF5 checkpointfile
+and then the index given to the :py:meth:`~.FlowSolver.load_state` method::
 
+    mesh2d = read_mesh_from_checkpoint(outputdir + '/hdf5/Velocity2d_155.h5')
+    ...set-up the thetis solver object with mesh2d...
     solver_obj.load_state(155)
 
 This also loads simulation time from the stored state.
```
However, when I was writing the docs, it didn't seem the most elegant of solutions. I wonder if we could instantiate the solver object with either a mesh object or a checkpoint file? Perhaps that's a job for later!

2023-08-03 09:15 UTC, stephankramer commented
Thanks Jon.

> However, when I was writing the docs, it didn't seem the most elegant of solutions. I wonder if we could instantiate the solver object with either a mesh object or a checkpoint file?

Yeah thought about that. The issue is that typically users need to do some set up that already requires the mesh, like creating a bathymetry function - also you wouldn't be able to provide the bathymetry as a function on creation. So then you would get something like:
```
solver_obj = FlowSolver2d('outputs/hdf5/Velocity2d_155.h5')
mesh2d = solver_obj.mesh2d
V = get_function_space(mesh2d, "CG", 1)
bathymetry = Function(V).interpolate(...)
solver_obj.set_bathymetry(bathymetry)
# or alternatively, something like
solver_obj.options.bathymetry = bathymetry
```

2023-08-03 10:19 UTC, jhill1 commented
Agreed; that is messier for more users, then the checkpointing issue. Let's stick with your solution. I can't approve the review, but I do approve

2023-08-03 14:45 UTC, jwallwork23 requested changes
Looks good. Just one minor request. Thanks!

2023-08-03 14:45 UTC, jwallwork23 commented on thetis/utility.py
> +    to pick up from the previous run.
This text is all really useful but could you break it into separate paragraphs?

2023-08-08 07:17 UTC, jwallwork23 approved these changes
Thanks! Just one very minor request but otherwise looks good to go.

2023-08-08 07:17 UTC, jwallwork23 commented on docs/Makefile
> +	for file in source/demos/*.py; do pylit -c $$file; mv $$file.txt $$file.rst; done
Would you mind adding `pylit` to `requirements.txt`?

2023-08-17 13:55 UTC, jwallwork23 approved these changes

2023-08-21 14:01 UTC, merged